---
- name: Automate Docker Container Management
  hosts: local
  become: false

  tasks:

    - name: Create and start Nginx container
      community.docker.docker_container:
        name: ansible-nginx
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8082:80"
